name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  flare_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


  assets:
   - assets/ant.flr
   - assets/cloudy.png
   - assets/foggy.png
   - assets/rainy.png
   - assets/snowy.png
   - assets/sunny.png
   - assets/thunderstorm.png
   - assets/windy.png



  fonts:
    - family: PressStart2P
      fonts:
        - asset: third_party/PressStart2P-Regular.ttf
